structure(list(url = "http://statistics.gov.scot/sparql", status_code = 400L, 
    headers = structure(list(server = "nginx", date = "Sun, 21 Jul 2019 17:19:32 GMT", 
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", status = "400 Bad Request", 
        `x-frame-options` = "SAMEORIGIN", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `cache-control` = "no-cache", 
        `x-request-id` = "c68e442a-b2e7-4c3b-b235-5c10fc0d8fed", 
        `x-runtime` = "0.019527"), class = c("insensitive", "list"
    )), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Sun, 21 Jul 2019 17:19:32 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            status = "400 Bad Request", `x-frame-options` = "SAMEORIGIN", 
            `x-xss-protection` = "1; mode=block", `x-content-type-options` = "nosniff", 
            `cache-control` = "no-cache", `x-request-id` = "c68e442a-b2e7-4c3b-b235-5c10fc0d8fed", 
            `x-runtime` = "0.019527"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"errors\":\"There was a syntax error in your query: Lexical error at line 1, column 13.  Encountered: \\\" \\\" (32), after : \\\"WRONG\\\"\"}"), 
    date = structure(1563729572, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.037958, 
    connect = 0.073053, pretransfer = 0.073152, starttransfer = 0.073162, 
    total = 0.127841)), class = "response")
