structure(list(url = "http://statistics.gov.scot/sparql", status_code = 400L, 
    headers = structure(list(server = "nginx", date = "Thu, 15 Aug 2019 18:32:15 GMT", 
        `content-type` = "application/json; charset=utf-8", status = "400 Bad Request", 
        `x-frame-options` = "SAMEORIGIN", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `cache-control` = "no-cache", 
        `x-request-id` = "35bed440-4674-46bc-bda6-be2c07664eeb", 
        `x-runtime` = "0.018864", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Thu, 15 Aug 2019 18:32:15 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            status = "400 Bad Request", `x-frame-options` = "SAMEORIGIN", 
            `x-xss-protection` = "1; mode=block", `x-content-type-options` = "nosniff", 
            `cache-control` = "no-cache", `x-request-id` = "35bed440-4674-46bc-bda6-be2c07664eeb", 
            `x-runtime` = "0.018864", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"errors\":\"There was a syntax error in your query: Lexical error at line 1, column 11.  Encountered: \\\" \\\" (32), after : \\\"TTTT\\\"\"}"), 
    date = structure(1565893935, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.381697, 
    connect = 6.498121, pretransfer = 6.498192, starttransfer = 6.4982, 
    total = 6.719372)), class = "response")
