# get_available_frameworks
# Returns available spatial frameworks

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?hierarchy
        ?label
WHERE { 
	?hierarchy  rdfs:subPropertyOf  <http://statistics.gov.scot/def/hierarchy/best-fit>
	;  rdfs:label ?label
}
