# The query gets dimensions of a specific data set

# Prefixes
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dim: <http://purl.org/linked-data/sdmx/2009/dimension#>


# Query
# For ?property will return labels of properties
# For ?p will return values

SELECT DISTINCT ?property ?label [where_label]
WHERE {
  ?x qb:dataSet <[data_set_uri]> .
  ?x ?property ?p .
  ?property rdfs:label ?label .
  [where_props]
}
