# qry_get_geography_data.sparql
# Fetch statistical data for:
# - selected geography framework
# - time period
# - selected indicator
# Used R function get_geography_data function.

# Query
SELECT DISTINCT [var_nms]
WHERE {

  [where_calls]
	
	[period]
}
