#' @title Pre-Process SPARQL Results Data
#'
#' @description The function takes data frame generated by one of the functions
#'   that sourced data from \href{http://statistics.gov.scot}{statistics.gov.scot}
#'   and returns pre-processed data set with the following changes.
#'
#' @param x A data frame, usually obtained via
#' @param clean_URI_strings Defaults to \code{TRUE}; removes
#'   \code{http://purl.org/linked-data/cube#} from
#'   \code{http://purl.org/linked-data/cube#Observation}.
#'
#' @return A data frame.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' pre_process_data(x = get_geography_data(data_set = "recorded-crime",
#'                                         geography = "Glasgow City",
#'                                         measure = "count"))
#' }
pre_process_data <- function(x, clean_URI_strings = TRUE) {
  # Check if provided object is data frame
  assert_data_frame(
    x = x,
    all.missing = FALSE,
    min.rows = 1,
    min.cols = 1,
    null.ok = FALSE
  )

  # Keep only last elemnt of URI
  if (clean_URI_strings) {
    x[] <- lapply(
      X = x,
      FUN = function(x) {
        sub(
          pattern = "^h.*(/|.*#)",
          replacement = "",
          x = x,
          perl = TRUE
        )
      }
    )
  }

  return(x)
}