# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname utility_functions
#' @section read_query_file: C++ fast cleaner for query text file removing
#'   comments and line breaks.
read_query_file <- function(file_path) {
    .Call(`_SmarterScotland_read_query_file`, file_path)
}

