# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname string_utilities
#' @param x A character vector
#' @section clean_URI_string: C++ fast cleaner for query text file removing
#'   comments and line breaks.
NULL

clean_URI_string <- function(x) {
    .Call(`_SmarterScotland_clean_URI_string`, x)
}

#' @rdname query_file_functions
#' @param file_path File path string to source
#' @section read_query_file: C++ fast cleaner for query text file removing
#'   comments and line breaks.
read_query_file <- function(file_path) {
    .Call(`_SmarterScotland_read_query_file`, file_path)
}

